### ISSUE TITLE
0.9.0 trows errors on build

### ISSUE THREAD

**Issue by bbaassssiiee** [chouseknecht/symfony-mariadb-nginx#2]
demo:base bas$ mkdir container
demo:base bas$ cd container/
demo:container bas$ ansible-container init
Ansible Container initialized.	
demo:container bas$ ls
ansible-requirements.txt	meta.yml
ansible.cfg			requirements.yml
container.yml
demo:container bas$ git init
Initialized empty Git repository in /Users/bas/base/container/.git/
demo:container bas$ git add .
demo:container bas$ git commit -m 'ansible-container init'
[master (root-commit) 5d6958a] ansible-container init
 5 files changed, 102 insertions(+)
 create mode 100644 ansible-requirements.txt
 create mode 100644 ansible.cfg
 create mode 100644 container.yml
 create mode 100644 meta.yml
 create mode 100644 requirements.yml
demo:container bas$ ls 
ansible-requirements.txt	meta.yml
ansible.cfg			requirements.yml
container.yml
demo:container bas$ ansible-container build
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/container/cli.py", line 259, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/container/core.py", line 133, in hostcmd_build
    conductor_container_id = engine_obj.get_container_id_for_service('conductor')
  File "/usr/local/lib/python2.7/site-packages/container/docker/engine.py", line 347, in get_container_id_for_service
    container_info = self.client.containers.get(self.container_name_for_service(service_name))
AttributeError: 'function' object has no attribute 'get'

**Comment by bbaassssiiee** [comment]
Can I use a git repo in ansible-container install?
Can I use -r requirements.yml -p roles in ansible-container install?
